## Extracting sentences from Estonian Reference Corpus

#### I Accessing corpus, choosing collection and layers

In [1]:
from estnltk import Text
from estnltk.storage.postgres import PostgresStorage

storage = PostgresStorage(pgpass_file='pgpass.txt', 
                          schema='estonian_text_corpora', 
                          role='estonian_text_corpora_read')

storage

INFO:storage.py:57: connecting to host: 'postgres.keeleressursid.ee', port: '5432', dbname: 'estonian-text-corpora', user: 'liivas'
INFO:storage.py:108: schema: 'estonian_text_corpora', temporary: False, role: 'estonian_text_corpora_read'

In [2]:
storage.collections

['koondkorpus_base_subset_of_5000_v2',
 'koondkorpus_base_v2',
 'koondkorpus_sentences',
 'koondkorpus_sentences_test_5000_sg_thread',
 'koondkorpus_syntax_subset',
 'koondkorpus_words_v16_1']

In [3]:
collection = storage['koondkorpus_sentences']

In [4]:
collection

Stanza syntax layer is selected, as it isn't among the default layers.

In [5]:
collection.selected_layers = ['v172_stanza_syntax']

In [6]:
len(collection)

21415543

In [ ]:
# example
collection[5]

Text(text='Bändi , mille solist ei osanud laulda , kidramees ei saanud keeltele pihta ja trummari eesmärk oli võimalikult palju müra teha .')

In [ ]:
# example of morphological analysis layer
collection[5].morph_analysis

Layer(name='morph_analysis', attributes=('normalized_text', 'lemma', 'root', 'root_tokens', 'ending', 'clitic', 'form', 'partofspeech'), spans=SL[Span('Bändi', [{'normalized_text': 'Bändi', 'lemma': 'bänd', 'root': 'bänd', 'root_tokens': ['bänd'], 'ending': '0', 'clitic': '', 'form': 'adt', 'partofspeech': 'S'}]),
Span(',', [{'normalized_text': ',', 'lemma': ',', 'root': ',', 'root_tokens': [','], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}]),
Span('mille', [{'normalized_text': 'mille', 'lemma': 'mis', 'root': 'mis', 'root_tokens': ['mis'], 'ending': '0', 'clitic': '', 'form': 'sg g', 'partofspeech': 'P'}, {'normalized_text': 'mille', 'lemma': 'mis', 'root': 'mis', 'root_tokens': ['mis'], 'ending': '0', 'clitic': '', 'form': 'pl g', 'partofspeech': 'P'}]),
Span('solist', [{'normalized_text': 'solist', 'lemma': 'solist', 'root': 'solist', 'root_tokens': ['solist'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'S'}]),
Span('ei', [{'normalized_text': 'ei', 'lemma': 'ei', 'root': 'ei', 'root_tokens': ['ei'], 'ending': '0', 'clitic': '', 'form': 'neg', 'partofspeech': 'V'}]),
Span('osanud', [{'normalized_text': 'osanud', 'lemma': 'oskama', 'root': 'oska', 'root_tokens': ['oska'], 'ending': 'nud', 'clitic': '', 'form': 'nud', 'partofspeech': 'V'}, {'normalized_text': 'osanud', 'lemma': 'osanud', 'root': 'osa=nud', 'root_tokens': ['osanud'], 'ending': 'd', 'clitic': '', 'form': 'pl n', 'partofspeech': 'A'}, {'normalized_text': 'osanud', 'lemma': 'osanud', 'root': 'osa=nud', 'root_tokens': ['osanud'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'A'}, {'normalized_text': 'osanud', 'lemma': 'osanud', 'root': 'osa=nud', 'root_tokens': ['osanud'], 'ending': '0', 'clitic': '', 'form': '', 'partofspeech': 'A'}]),
Span('laulda', [{'normalized_text': 'laulda', 'lemma': 'laulma', 'root': 'laul', 'root_tokens': ['laul'], 'ending': 'da', 'clitic': '', 'form': 'da', 'partofspeech': 'V'}]),
Span(',', [{'normalized_text': ',', 'lemma': ',', 'root': ',', 'root_tokens': [','], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}]),
Span('kidramees', [{'normalized_text': 'kidramees', 'lemma': 'kidramees', 'root': 'kidra_mees', 'root_tokens': ['kidra', 'mees'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'S'}]),
Span('ei', [{'normalized_text': 'ei', 'lemma': 'ei', 'root': 'ei', 'root_tokens': ['ei'], 'ending': '0', 'clitic': '', 'form': 'neg', 'partofspeech': 'V'}]),
Span('saanud', [{'normalized_text': 'saanud', 'lemma': 'saama', 'root': 'saa', 'root_tokens': ['saa'], 'ending': 'nud', 'clitic': '', 'form': 'nud', 'partofspeech': 'V'}, {'normalized_text': 'saanud', 'lemma': 'saanud', 'root': 'saa=nud', 'root_tokens': ['saanud'], 'ending': '0', 'clitic': '', 'form': '', 'partofspeech': 'A'}, {'normalized_text': 'saanud', 'lemma': 'saanud', 'root': 'saa=nud', 'root_tokens': ['saanud'], 'ending': 'd', 'clitic': '', 'form': 'pl n', 'partofspeech': 'A'}, {'normalized_text': 'saanud', 'lemma': 'saanud', 'root': 'saa=nud', 'root_tokens': ['saanud'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'A'}]),
Span('keeltele', [{'normalized_text': 'keeltele', 'lemma': 'keel', 'root': 'keel', 'root_tokens': ['keel'], 'ending': 'tele', 'clitic': '', 'form': 'pl all', 'partofspeech': 'S'}]),
Span('pihta', [{'normalized_text': 'pihta', 'lemma': 'pihta', 'root': 'pihta', 'root_tokens': ['pihta'], 'ending': '0', 'clitic': '', 'form': '', 'partofspeech': 'D'}]),
Span('ja', [{'normalized_text': 'ja', 'lemma': 'ja', 'root': 'ja', 'root_tokens': ['ja'], 'ending': '0', 'clitic': '', 'form': '', 'partofspeech': 'J'}]),
Span('trummari', [{'normalized_text': 'trummari', 'lemma': 'trummar', 'root': 'trummar', 'root_tokens': ['trummar'], 'ending': '0', 'clitic': '', 'form': 'sg g', 'partofspeech': 'S'}]),
Span('eesmärk', [{'normalized_text': 'eesmärk', 'lemma': 'eesmärk', 'root': 'ees_märk', 'root_tokens': ['ees', 'märk'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'S'}]),
Span('oli', [{'normalized_text': 'oli', 'lemma': 'olema', 'root': 'ole', 'root_tokens': ['ole'], 'ending': 'i', 'clitic': '', 'form': 's', 'partofspeech': 'V'}]),
Span('võimalikult', [{'normalized_text': 'võimalikult', 'lemma': 'võimalikult', 'root': 'võimalikult', 'root_tokens': ['võimalikult'], 'ending': '0', 'clitic': '', 'form': '', 'partofspeech': 'D'}]),
Span('palju', [{'normalized_text': 'palju', 'lemma': 'palju', 'root': 'palju', 'root_tokens': ['palju'], 'ending': '0', 'clitic': '', 'form': '', 'partofspeech': 'D'}]),
Span('müra', [{'normalized_text': 'müra', 'lemma': 'müra', 'root': 'müra', 'root_tokens': ['müra'], 'ending': '0', 'clitic': '', 'form': 'sg p', 'partofspeech': 'S'}]),
Span('teha', [{'normalized_text': 'teha', 'lemma': 'tegema', 'root': 'tege', 'root_tokens': ['tege'], 'ending': 'a', 'clitic': '', 'form': 'da', 'partofspeech': 'V'}]),
Span('.', [{'normalized_text': '.', 'lemma': '.', 'root': '.', 'root_tokens': ['.'], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}])])

In [ ]:
# example of Stanza syntax layer
collection[5].v172_stanza_syntax

Layer(name='v172_stanza_syntax', attributes=('id', 'lemma', 'upostag', 'xpostag', 'feats', 'head', 'deprel', 'deps', 'misc', 'parent_span', 'children'), spans=SL[Span('Bändi', [{'id': 1, 'lemma': 'bänd', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'adit': 'adit'}, 'head': 11, 'deprel': 'obj', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span(',', [{'id': 2, 'lemma': ',', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 4, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('mille', [{'id': 3, 'lemma': 'mis', 'upostag': 'P', 'xpostag': 'P', 'feats': {'pl': 'pl', 'gen': 'gen'}, 'head': 4, 'deprel': 'nmod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('solist', [{'id': 4, 'lemma': 'solist', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'nom': 'nom'}, 'head': 6, 'deprel': 'nsubj', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('ei', [{'id': 5, 'lemma': 'ei', 'upostag': 'V', 'xpostag': 'V', 'feats': {'aux': 'aux', 'neg': 'neg'}, 'head': 6, 'deprel': 'aux', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('osanud', [{'id': 6, 'lemma': 'oskama', 'upostag': 'V', 'xpostag': 'V', 'feats': {'ps': 'ps', 'mod': 'mod', 'past': 'past', 'partic': 'partic'}, 'head': 1, 'deprel': 'acl:relcl', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('laulda', [{'id': 7, 'lemma': 'laulma', 'upostag': 'V', 'xpostag': 'V', 'feats': {'aux': 'aux', 'inf': 'inf'}, 'head': 6, 'deprel': 'xcomp', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span(',', [{'id': 8, 'lemma': ',', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 6, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('kidramees', [{'id': 9, 'lemma': 'kidramees', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'nom': 'nom'}, 'head': 11, 'deprel': 'nsubj', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('ei', [{'id': 10, 'lemma': 'ei', 'upostag': 'V', 'xpostag': 'V', 'feats': {'aux': 'aux', 'neg': 'neg'}, 'head': 11, 'deprel': 'aux', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('saanud', [{'id': 11, 'lemma': 'saama', 'upostag': 'V', 'xpostag': 'V', 'feats': {'ps': 'ps', 'aux': 'aux', 'past': 'past', 'partic': 'partic'}, 'head': 0, 'deprel': 'root', 'deps': '_', 'misc': '_', 'parent_span': None, 'children': <class 'tuple'>}]),
Span('keeltele', [{'id': 12, 'lemma': 'keel', 'upostag': 'S', 'xpostag': 'S', 'feats': {'pl': 'pl', 'all': 'all', 'com': 'com'}, 'head': 11, 'deprel': 'obl', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('pihta', [{'id': 13, 'lemma': 'pihta', 'upostag': 'D', 'xpostag': 'D', 'feats': {}, 'head': 11, 'deprel': 'compound:prt', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('ja', [{'id': 14, 'lemma': 'ja', 'upostag': 'J', 'xpostag': 'J', 'feats': {'crd': 'crd', 'sub': 'sub'}, 'head': 17, 'deprel': 'cc', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('trummari', [{'id': 15, 'lemma': 'trummar', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'gen': 'gen'}, 'head': 16, 'deprel': 'nmod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('eesmärk', [{'id': 16, 'lemma': 'eesmärk', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'nom': 'nom'}, 'head': 17, 'deprel': 'nsubj', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('oli', [{'id': 17, 'lemma': 'olema', 'upostag': 'V', 'xpostag': 'V', 'feats': {'af': 'af', 'ps': 'ps', 'sg': 'sg', 'ps3': 'ps3', 'impf': 'impf', 'main': 'main', 'indic': 'indic'}, 'head': 11, 'deprel': 'conj', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('võimalikult', [{'id': 18, 'lemma': 'võimalikult', 'upostag': 'D', 'xpostag': 'D', 'feats': {}, 'head': 19, 'deprel': 'advmod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('palju', [{'id': 19, 'lemma': 'palju', 'upostag': 'D', 'xpostag': 'D', 'feats': {}, 'head': 20, 'deprel': 'advmod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('müra', [{'id': 20, 'lemma': 'müra', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'part': 'part'}, 'head': 21, 'deprel': 'obj', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('teha', [{'id': 21, 'lemma': 'tegema', 'upostag': 'V', 'xpostag': 'V', 'feats': {'inf': 'inf', 'mod': 'mod'}, 'head': 17, 'deprel': 'ccomp', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('.', [{'id': 22, 'lemma': '.', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 11, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}])])

#### II Extracting sentences that contain candidates for elative construction examples

In [ ]:
import sys

sys.path.append("..")

import time


# Collecting sentences and their indexes
extracted_examples = []
collection_indexes = []

start_time = time.time()

for sent_idx, sent_obj in enumerate(collection):

    words = sent_obj.v172_stanza_syntax
    
    for stanza_word in words:
        
        # Early stopping if word is not a nominal modifier
        if stanza_word.deprel != "nmod":
            continue

        morph = stanza_word.morph_analysis
        pos = morph.partofspeech
        form = morph.form

        # Early stopping if nominal modifier is not a substantive or isn't in singular elative case
        if "S" not in pos or "sg el" not in form:
            continue
       
        parent = stanza_word.parent_span

        # Early  stopping if nominal modifier doesn't have a syntactic parent
        if parent is None:
            continue
        
        parent_pos = parent.morph_analysis.partofspeech

        # Early stopping if parent is not a substantive or proper noun
        if not ("S" in parent_pos or "H" in parent_pos):
            continue
        
        # saving sentence Text-object and its index
        extracted_examples.append(sent_obj)
        collection_indexes.append(sent_idx)
        break

print("--- %s seconds ---" % (time.time() - start_time))

storage.close()

from estnltk_core.converters.json_exporter import text_to_json

# Saving extracted sentences in JSON-format
output_dir = "../data/koondkorpus_sentences/conx_example_sentences_20042026/"

for idx, example in enumerate(extracted_examples):
    example.meta["sentence_id"] = collection_indexes[idx]
    text_to_json(example, f"{output_dir}{collection_indexes[idx]}.json")

OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.